/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biendaiduong;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class DaiDuong extends javax.swing.JPanel {

    /**
     * Creates new form DaiDuong
     */
    Graphics g;
    Ca player;
    ArrayList<Ca> calon;
    ArrayList<Ca> cabe;
    int size = 5;

    public DaiDuong() {
        initComponents();
        //g = this.getGraphics();
        //this.setBackground(Color.CYAN);
        setup();
        repaint();
    }

    void setup() {
        player = new Ca("", 100, 100, 100, 100);
        calon = new ArrayList<>();
        cabe = new ArrayList<>();
        for (int i = 0; i < size; i++) {
            Random obj = new Random();
            int x = obj.nextInt(1500);
            obj = new Random();
            int y = obj.nextInt(800);
            Ca c = new Ca("", x, y, 100, 80);
            c.t = new Thread(new Runnable() {
                @Override
                public void run() {
                    while (true) {
                        try {
                            Random r = new Random();
                            int newx = r.nextInt(20);
                            int newy = r.nextInt(20);
                            r = new Random();
                            int huong = r.nextInt(4);
                            if (huong == 0) {//trai
                                int i = 0;
                                do {
                                    if (c.x > 10) {
                                        c.x = c.x - newx;
                                    }
                                    i++;
                                    Thread.sleep(20);
                                } while (i <= newx);
                            }
                            if (huong == 1) {//phai
                                int i = 0;
                                do {
                                    if (c.x < 1800) {
                                        c.x = c.x + newx;
                                    }
                                    i++;
                                    Thread.sleep(20);
                                } while (i <= newx);
                            }
                            if (huong == 2) {//len
                                int i = 0;
                                do {
                                    if (c.y > 10) {
                                        c.y = c.y - newy;
                                    }
                                    i++;
                                    Thread.sleep(20);
                                } while (i <= newy);
                            }
                            if (huong == 3) {
                                int i = 0;
                                do {
                                    if (c.y < 950) {
                                        c.y = c.y + newy;
                                    }
                                    i++;
                                    Thread.sleep(20);
                                } while (i <= newy);
                            }
                            repaint();

                        } catch (Exception e) {

                        }
                    }

                }
            });
            c.t.start();
            calon.add(c);
        }
        for (int i = 0; i < size; i++) {
            Random obj = new Random();
            int x = obj.nextInt(1500);
            obj = new Random();
            int y = obj.nextInt(800);
            cabe.add(new Ca("", x, y, 40, 30));
        }

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        //hinh o day
        Dimension d = getSize();

        ImageIcon icon = new ImageIcon("C:\\Users\\ASUS\\Downloads\\pexels-eberhard-grossgasteiger-1064162.jpg");
        Image img = icon.getImage();
        g.drawImage(img, 0, 0, d.width, d.height, null);
        player.drawCa(g, "C:\\Users\\ASUS\\Downloads\\ca4.jpg");

         for (Ca c : calon) {
            c.drawCa(g,"C:\\Users\\ASUS\\Downloads\\ca3.png");
        }
        for (Ca c : cabe) {
            c.drawCa(g,"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
